django-book-reviews/bookreviews/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('reviews/', include('reviews.urls')),
    path('admin/', admin.site.urls),
]

homepage/urls.py
from django.urls import path

from . import views


app_name = "homepage"
urlpatterns = [
    path("", views.index, name="homepage"),
]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls')),
    path('reviews/', include('reviews.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path

from . import views

app_name = "reviews"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name="review")
]

homepage/models.py
from django.db import models

# Create your models here.

reviews/models.py
from datetime import datetime
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from pkg_resources import require
from taggit.managers import TaggableManager
from django.contrib import admin
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

class Review(models.Model):
    post_date = models.DateField(
        'Date of Review',
    )
    post_slug = models.CharField("Slug", max_length=255, null=True)

    review_preview_text = models.TextField(
        'Preview Text',
        max_length=255, 
        default="",
        null=True,
        help_text="Max 255 characters"
    )
    book_title = models.CharField("Title", max_length=255)
    book_subtitle = models.CharField("Subtitle", max_length=255, blank=True, null=True)
    book_author = models.CharField("Author",max_length=255, blank=True, null=True)

    # cover image with its transformations
    book_cover_image = models.ImageField("Cover Image",upload_to='images/', default="", blank=True, null=True)
    book_cover_thumbnail = ImageSpecField([ResizeToFill(200,292)], source='book_cover_image', format='JPEG',
                                          options={'quality': 75})

    book_star_rating = models.IntegerField(
        "Star Rating",
        null=True,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ]
    )
    book_review_body_text = models.TextField("Review Text", blank=True, null=True)
    topic_tags = TaggableManager("Topic Tags", blank=True)

    def __str__(self):
        if len(self.book_subtitle) > 0: 
            return self.book_title + ": " + self.book_subtitle
        else:
            return self.book_title


    @admin.display(        
        ordering='book_title',
        description='Title',
    )
    def full_title(self) -> str: 
        if self.book_subtitle != None:
            return self.book_title + ": " + self.book_subtitle
        else:
            return self.book_title

homepage/views.py
from django.shortcuts import render


def index(request):
    return render(request, "homepage/index.html", context={})

reviews/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Review

class IndexView(generic.ListView):
    template_name = "reviews/index.html"
    context_object_name = "reviews_list"

    def get_queryset(self):
        """Return the last five book reviews"""
        return Review.objects.order_by('-post_date')[:5]


class DetailView(generic.DetailView):
    model = Review
    template_name = 'reviews/review.html'

homepage/templates/homepage/index.html
{% extends "theme/base.html" %}

{% block content %}

testing

{% endblock %}

reviews/templates/reviews/_layout.html
{% load static %}
{% load tailwind_tags %}

<!DOCTYPE html>
<html>
    <head>
        <title>Nathan's Book Reviews</title>
        <link rel="stylesheet" type="text/css" href="{% static 'reviews/style.css' %}">
        {% tailwind_css %}
    </head>
<body>

    <div class="wrapper">
        {% block content %}{% endblock %}
    </div>    
</body>
</html>

reviews/templates/reviews/index.html
{% extends "theme/base.html" %}

{% block content %}
<h1>Book Reviews</h1>
{% if reviews_list %}
    <ul>
        {% for review in reviews_list  %}
            <li> 
                <a href="{% url 'reviews:review' review.id %}">
                    {{ review.book_title }}
                </a>                
            </li>
        {% endfor %}    
    </ul>
    
{% endif %}
{% endblock %}

reviews/templates/reviews/review.html
{% extends "theme/base.html" %}

{% block content %}
    <div class="bg-gray-100 p-4">
        {% if review %}
            <h1>Title: {{ review.book_title }}</h1>
            <p>Author: {{ review.book_author }}</p>
            <p>Review: {{ review.book_review }}</p>
            {% if review.book_cover_image %}
                <img
                    src="{{ review.book_cover_thumbnail.url }}"
                    alt="Book cover for {{ review.book_title }} by {{ review.book_author }}" />
            {% endif %}
        {% endif %}
    </div>

{% endblock %}

theme/templates/theme/base.html
{% load static %}
{% load tailwind_tags %}

<!DOCTYPE html>
<html>
    <head>
        <title>Nathan's Book Reviews</title>

        {# Google Fonts #}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Homemade+Apple&display=swap" rel="stylesheet">

        {% tailwind_css %}
    </head>
<body class="bg-white">
    <div class="sticky w-full shadow">
        <div class="max-w-3xl mx-auto py-8 px-2 flex flex-col items-center">
            <img src="{% static 'Nathan-Pacific-Ocean-Circle.png' %}" class="w-36 h-36 mb-4" />
            <div class="mr-6 font-handwriting font-bold text-4xl">Nathan's Book Reviews</div>
        </div>
    </div>

    <div class="wrapper">
        <section class="bg-gray-100">
            {% block content %}{% endblock %}
        </section>
    </div>

</body>
</html>